<?php

namespace App\Form;

use App\Classe\Search;
use App\Entity\Category;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use function Sodium\add;

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('string', TextType::class, [
                'label' => 'Rechercher', //ou bien (false)
                'required' => false,
                'attr' => [
                'placeholder' => 'Votre recherche ...',
                    'class' => 'form-control-sm',
                    ]
    ])

            ->add('categories',EntityType::class, [
                'label' => false,
                'required' => false,
                'class' => Category::class,
                'multiple' => true,
                'expanded' =>true,

            ])
            ->add('submit', SubmitType::class,[
                'label' =>'Filter',
                'attr' => [
                    'class' => 'btn-block btn-info'
                ]
            ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Search::class,
            'method' => 'GET',
            'csrf_protection' => false,

        ]);
    }
     public function getBlockPrefix()
{
//    return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    return '';
}


}
